name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
      - name: Setup Nuget
        uses: nuget/setup-nuget@v1     
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
      - name: Restore NuGet packages
        run: nuget restore "SugestaoDeProdutos.sln"
      
      - name: Build Debug
        run: msbuild "SugestaoDeProdutos.sln" /p:Configuration=Debug
