name: Build & Bump Version

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
    paths-ignore:
      - "**/Properties/AssemblyInfo.cs"
      - "**/Properties/Version.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GHA_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  updateVersion:
    name: Build & Patch
    runs-on: self-hosted
    permissions:
      pull-requests: write

    steps:

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update PR with comment (build started)
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          refresh-message-position: true
          message-id: 'begin'
          message: |
            **Build debug & Version bump:** :beginner: [Build started](${{ env.GHA_URL }})

      - name: Generate check
        uses: LouisBrunner/checks-action@v1.6.2
        id: generate_check
        if: always()
        with:
          token: ${{ steps.generate_token.outputs.token }}
          name: 'Build & Bump Version'
          status: 'in_progress'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set solution name
        run: |
          echo "solution=$([io.path]::GetFileNameWithoutExtension($(Get-ChildItem -Path .\* -Include *.sln)))" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "projectPath=$((Get-ChildItem -Path .\Src\ -Directory | Select-Object -First 1).Name)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Update PR with comment (build started solution)
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          refresh-message-position: true
          message-id: 'begin'
          message: |
            **Build debug & Version bump:** :beginner: [Building ${{ env.solution }}.sln](${{ env.GHA_URL }})

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3
        with:
          msbuild-architecture: x64
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Restore NuGet packages
        run: nuget restore "${{ env.solution }}.sln"

      - name: Build Debug
        run: msbuild "${{ env.solution }}.sln" /p:Configuration=Debug  -verbosity:detailed

      - name: Set version from file
        run: |
          echo "version=$(type Src/${{ env.projectPath }}/Properties/Version.txt)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Update PR with comment (version)
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          refresh-message-position: true
          message-id: 'version'
          message: |
            **Build debug & Version bump:** :dart: [Build succeeded](${{ env.GHA_URL }}) - New version: ${{ env.version }}

      - name: Set check as successfully before new commit
        uses: LouisBrunner/checks-action@v1.6.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          conclusion: 'success'
          check_id: ${{ steps.generate_check.outputs.check_id }}
          output: |
            {"summary":"New version: ${{ env.version }}"}

      - name: Setup GIT config
        run: |
          git config user.name "net-framework-updater[bot]"
          git config user.email "136581072+net-framework-updater[bot]@users.noreply.github.com"
          git config --global --add --bool push.autoSetupRemote true

      - name: Commit and Push
        run: |
          git add .
          git commit -a -m "Version bump (CI)"
          echo "sha1=$(git rev-parse HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Append
          git push
          
      - name: Update PR with comment
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          refresh-message-position: true
          message-id: 'final'
          message: |
            **Build debug & Version bump:** :white_check_mark: [Successfully builded and patched](${{ env.GHA_URL }}) **${{ env.solution }}.sln**.
            
            Current version: **${{ env.version }}**
          message-failure: |
            **Build debug & Version bump:** :x: [Failed](${{ env.GHA_URL }})
          message-cancelled: |
            **Build debug & Version bump:** :o: [Cancelled](${{ env.GHA_URL }})

      - name: Sleep for 5 seconds
        run: Start-Sleep -s 5
        shell: powershell

      - name: Set check as successfully after new commit
        uses: LouisBrunner/checks-action@v1.6.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          conclusion: 'success'
          name: 'Build & Bump Version'
          output: |
            {"summary":"New version: ${{ env.version }}"}

      - name: Update check run status (Success)
        uses: guibranco/github-status-action-v2@v1.1.7
        if: success()
        with:
          authToken: ${{ steps.generate_token.outputs.token }}
          context: 'Build & Bump Version'
          description: 'Build ${{ env.solution}}.sln - Version: ${{ env.version }}'
          state: 'success'
          sha: ${{ env.sha1 }}
          target_url: ${{ env.GHA_URL }}

      - name: Update check run status (Failure or Cancellation)
        uses: guibranco/github-status-action-v2@v1.1.7
        if: failure() || cancelled()
        with:
          authToken: ${{ steps.generate_token.outputs.token }}
          context: 'Build & Bump Version'
          description: ${{ job.status }}
          state: 'failure'
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: ${{ env.GHA_URL }}      
