name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Restore NuGet Packages
        run: nuget restore "SugfestaoDeProdutos.sln"

      - name: Build Release
        run: msbuild "SugfestaoDeProdutos.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderPublish /p:RestoreLockedMode=true

      - name: Upload Core artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Core
          path: Publish\Core      
    
  deploy_core:
    name: Deploy Core
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Core

      - name: Upload to ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: Core
          forceSsl: true 

  create_release:
    name: Create Release
    needs: [deploy_core, deploy_assets]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact Core
        uses: actions/download-artifact@v2
        with:
          name: Core
          path: Core
    
      - name: Zip artifact
        run: |
          zip -r Core.zip ./Core/*
                    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: New release of Sugestão de Produtos
          draft: false
          prerelease: false

      - name: Upload Release Asset Core
        id: upload_release_asset_core
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Core.zip
          asset_name: Core.zip
          asset_content_type: application/zip

      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.RELEASE_WEBHOOK_URL }}
          webhook_secret: '{"x-github-release-token": "${{ secrets.RELEASE_WEBHOOK_TOKEN }}"}'
          data: '{"downloadUrls": ["${{ steps.upload_release_asset_core.outputs.browser_download_url }}"]}'
