name: Label based on PR size

on:
  pull_request:
  workflow_dispatch:

jobs:
  size-label:
    permissions: write-all
    runs-on: self-hosted

    steps:

      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
